#pragma config(Motor,  port2,           backRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeftMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/************************************/
/*  Nicholas Dyer                   */
/*  KiwiBot Code                    */
/*  Version 0.3                     */
/*  Last Worked: 11/29/18           */
/************************************/


//Define Joystick Variables
float joyRightX;
float joyRightY;
float joyLeftX;
float joyLeftY;

//Define Button Variables
int rightBumper;
int leftBumper;

//Define Motor Value Variables
int frontMotorValue;
int backLeftMotorValue;
int backRightMotorValue;

//Define Variables for Polar Vectors
float phi;
float rValue;

//Define Angle Constants
float topAngle = (90*3.14159265358979)/180;
float backLeftAngle = (210*3.14159265358979)/180;
float backRightAngle = (330*3.14159265358979)/180;

void getController() //Update all Joystick and Button Variables
{
	joyRightX = vexRT[Ch1];
	joyRightY = vexRT[Ch2];
	joyLeftX = vexRT[Ch4];
	joyLeftY = vexRT[Ch3];

	rightBumper = vexRT[Btn6U];
	leftBumper = vexRT[Btn5U];
}

void handleTranslate() //Handle Translate Driving
{
	//Set Up Variables for Polar Coordinates
	phi = atan2(joyRightY, joyRightX);
	rValue = sqrt((joyRightX*joyRightX)+(joyRightY*joyRightY));

	//Set the Value of the Motors
	frontMotorValue = sin(topAngle-phi)*rValue;
	backLeftMotorValue = sin(backLeftAngle-phi)*rValue;
	backRightMotorValue = sin(backRightAngle-phi)*rValue;
}

void handleArcade() //Handle Arcade Driving
{
	//Set the Motors to a Simple Arcade Mode
	frontMotorValue = joyLeftX; //Front Wheel for Left and Right
	backRightMotorValue = joyLeftY; //Back Two Wheels for Forward and Backwards
	backRightMotorValue = -joyLeftY;
}

void handleSpin() //Handle Spinning
{
	if (rightBumper == 1) //If the Right Bumper is Pressed
	{
		frontMotorValue = 127; //Spin Clockwise
		backRightMotorValue = 127;
		backLeftMotorValue = 127;
	}
	if (leftBumper == 1) //If the Left Bumper is Pressed
	{
		frontMotorValue = -127; //Spin Counter-Clockwise
		backRightMotorValue = -127;
		backLeftMotorValue = -127;
	}
}

void pushMotorValues() //Set the Motors to their Values
{
	motor[frontMotor] = frontMotorValue;
	motor[backLeftMotor] = backLeftMotorValue;
	motor[backRightMotor] = backRightMotorValue;
}


task main()
{
	while(1==1) //Main Loop
	{
		getController();
		//handleArcade();
		handleTranslate();
		handleSpin();
		pushMotorValues();
	}
}
