#pragma config(Motor,  port2,           backRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeftMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/************************************/
/*	Nicholas Dyer										*/
/*	KiwiBot Code										*/
/*	Version 0.1											*/
/*	Last Worked: 11/29/18						*/
/************************************/

float joyRightX;
float joyRightY;
float joyLeftX;
float joyLeftY;

int rightBumper;
int leftBumper;

int frontMotorValue;
int backLeftMotorValue;
int backRightMotorValue;

float phi;
float rValue;

float topAngle = degreesToRadians(90);
float backLeftAngle = degreesToRadians(210);
float backRightAngle = degreesToRadians(330);

void getController()
{
	joyRightX = vexRT[Ch1];
	joyRightY = vexRT[Ch2];
	joyLeftX = vexRT[Ch4];
	joyLeftY = vexRT[Ch3];

	rightBumper = vexRT[Btn6U];
	leftBumper = vexRT[Btn5U];
}

void handleTranslate()
{
	phi = atan2(joyRightX, joyRightY);
	rValue = sqrt((pow(joyRightY,2))+(pow(joyRightX,2)));

	frontMotorValue = sin(topAngle-phi)*rValue;
	backLeftMotorValue = sin(backLeftAngle-phi)*rValue;
	backRightMotorValue = sin(backRightAngle-phi)*rValue;
}

void handleArcade()
{
	frontMotorValue = joyLeftX;
	backRightMotorValue = joyLeftY;
	backRightMotorValue = -joyLeftY;
}

void handleSpin()
{
	if (rightBumper == 1)
	{
		frontMotorValue = 127;
		backRightMotorValue = 127;
		backRightMotorValue = 127;
	}
	else if (leftBumper == 1)
	{
		frontMotorValue = -127;
		backRightMotorValue = -127;
		backRightMotorValue = -127;
	}
	else
	{
		frontMotorValue = frontMotorValue;
		backRightMotorValue = backRightMotorValue;
		backRightMotorValue = backRightMotorValue;
	}
}

void pushMotorValues()
{
	motor[frontMotor] = frontMotorValue;
	motor[backLeftMotor] = backLeftMotorValue;
	motor[backRightMotor] = backRightMotorValue;
}


task main()
{
	while(1==1)
	{
		getController();
		handleArcade();
		handleTranslate();
		handleSpin();
		pushMotorValues();
	}
}
