#pragma config(Sensor, dgtl5,  lSwitch,        sensorTouch)
#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           flywheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           conveyor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           ballLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightDrive,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**************************************************************************/
/*	Nicholas Dyer																													*/
/*	CBNA Robotics 2018-2019																								*/
/*	Launcher Program Version 0.2																					*/
/*	Last Worked 11/30/2018																								*/
/**************************************************************************/

//Set Constants
int deadzoneValue = 20;
int drivePower = 100;
int conveyorSpeed = 127;
int pulleySpeed = 127;

//Define Controller Variables
int rightBumpUp;
int rightBumpDown;
int leftBumpUp;
int leftBumpDown;
int leftUp;
int leftDown;
int leftLeft;
int leftRight;
float joyRight;
float joyLeft;

//Define Motor Value Variables
int flyValue;
int leftDriveValue;
int rightDriveValue;
int conveyorValue;

void handleControl()
{
	//Set Controller Values to Variables
	rightBumpUp = vexRT[Btn6U];
	rightBumpDown = vexRT[Btn6D];
	leftBumpUp = vexRT[Btn5U];
	leftBumpDown = vexRT[Btn5D];

	leftUp = vexRT[Btn7U];
	leftDown = vexRT[Btn7D];
	leftLeft = vexRT[Btn7L];
	leftRight = vexRT[Btn7R];

	joyLeft = vexRT[Ch3];
	joyRight = vexRT[Ch2];
}

void handleTank()
{
	//Control Right Joystick + Deadzone
	if (abs(joyLeft) >= deadzoneValue) //Check Deadzone
	{
		leftDriveValue = joyLeft*(drivePower/100);
	}
	else
	{
		leftDriveValue = 0;
	}

	//Control Right Joystick + Deadzone
	if (abs(joyRight) >= deadzoneValue) //Check Deadzone
	{
		rightDriveValue = joyRight*(drivePower/100);
	}
	else
	{
		rightDriveValue = 0;
	}
}


void handleFlywheel() //Flywheel Control
{
	if (leftUp == 1)
	{
		flyValue = 127; //If the left up button is pressed, set flywheel to max speed
	}
	if (leftDown == 1)
	{
		flyValue = 0; //If the left down button is pressed, turn the flywheel off
	}
	if (leftLeft == 1 && time1[T1] > 500)	//If the left left button is pressed
	{																			//and has not been pressed in the
		flyValue = flyValue-22;							//last 30 milliseconds, decrease the flywheel
		clearTimer(T1);											//speed by 32.
	}
	if (leftRight == 1 && time1[T1] > 500)//If the left right button is pressed
	{																			//and has not been pressed in the
		flyValue = flyValue+22;							//last 30 milliseconds, increase the flywheel
		clearTimer(T1);											//speed by 32.
	}
	if (flyValue < 0) //If the flywheel value is set below zero, force the value to zero.
	{
		flyValue = 0;
	}
	if (flyValue > 127) //If the flywheel value is set above 127, force the value to 127.
	{
		flyValue = 127;
	}
}

void handleConveyor()
{
	if (rightBumpUp == 1)
	{
		conveyorValue = conveyorSpeed; //If the right up bumper is pressed, make the conveyor go up
	}
	if (rightBumpDown == 1)
	{
		conveyorValue = 0; //If the right down bumper is pressed, make the conveyor stop
	}
}

void handleMotor() //Set motors to their values
{
	motor[conveyor] = conveyorValue;
	motor[flywheel] = flyValue;
	motor[leftDrive] = leftDriveValue;
	motor[rightDrive] = rightDriveValue;
}

task main()
{
	while(1==1) //Main Loop
	{
		handleControl();
		handleTank();
		handleFlywheel();
		handleConveyor();
		handleMotor();
	}
}
